language: python
python: 
 - 2.7
 - 3.6.0
cache: pip
install:
 - pip install -r requirements.txt
script:
 - python run.py
deploy:
 - provider: script 
   script: bash scripts/deploy.sh staging
   on:
    branch: develop
  # deploy master to production
 - provider: script
   script: bash scripts/deploy.sh production
   on:
    branch: master
